### ISSUE TITLE
Como começar com javascript

### ISSUE THREAD

**Issue by felipeacelino** [akfzambrana/dicas-de-frontend#1]
First! Brincadeira hahaha...

Primeiramente, parabéns pela iniciativa Andréa. Estou iniciando minha carreira no Front e confesso que estou meio assustado com esse tal de javascript e seus trilhões de frameworks e bibliotecas. Tem alguma dica para quem está começando como o que estudar, onde estudar, etc. Qual quer dica já ta valendo! =)

**Comment by akfzambrana** [comment]
Começa pelo básico que é o estudo de lógica e daí estuda a linguagem em sí. 
A dica de ouro é q "Quando vc sabe a base o restante fica mais facil de estudar/aprender" e Lógica é a base de tudo na computação, depois disso vem as linguagens e talz. 
Um colega que eu acho um dos melhores programadores que já conheci ele sempre diz que "quando vc sabe programar, aprender a sintaxe é dois palitos" e só se aprende a programar com lógica pura, nua e crua.

O William Oliveira escreveu sobre algumas coisas interessantes no blog dele, se liga:
- https://woliveiras.com.br/posts/Introducao-ao-Raciocinio-Logico/
- https://woliveiras.com.br/posts/Links-uteis-para-aprender-se-aprofundar-ou-manter-se-atualizado-sobre-JavaScript/
- https://woliveiras.com.br/posts/Livros-sobre-JavaScript-do-iniciante-ao-avancado-e-ES6/

Tem este guia que é bem interessante http://jlcarvalho.github.io/guia-frontend/

E tem um projeto de Mentoria que é bem legal especialmente pra guiar seus passos: https://github.com/training-center/mentoria
